services:
  threadwork:
    build: .
    container_name: threadwork-container
    ports:
      - "8000:8000"
      - "5174:5174"
    volumes:
      - .:/app
    command: python /app/server.py
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:

# To build and run the container:
# docker-compose up --build
#
# To restart the container after making changes:
# docker-compose restart 

# to remove container
# docker rm threadwork-container

# to remove image
# docker rmi threadwork-image

# to remove all containers
# docker rm $(docker ps -a -q)
