services:
  threadwork:
    build: .
    container_name: threadwork-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Run main.py without using watchgod. You'll need to restart the container manually
    command: python /app/main.py 